#!/bin/bash

echo 'Workload	Concurrency	My./MyCPUBench cpuBenchValue	TheoreticalValue		Efficiency'

./MyCPUBench cpu_DP_1thread.dat >> out.txt
./MyCPUBench cpu_DP_2thread.dat >> out.txt
./MyCPUBench cpu_DP_4thread.dat >> out.txt
./MyCPUBench cpu_HP_1thread.dat >> out.txt
./MyCPUBench cpu_HP_2thread.dat >> out.txt
./MyCPUBench cpu_HP_4thread.dat >> out.txt
./MyCPUBench cpu_QP_1thread.dat >> out.txt
./MyCPUBench cpu_QP_2thread.dat >> out.txt
./MyCPUBench cpu_QP_4thread.dat >> out.txt
./MyCPUBench cpu_SP_1thread.dat >> out.txt
./MyCPUBench cpu_SP_2thread.dat >> out.txt
./MyCPUBench cpu_SP_4thread.dat >> out.txt
./MyCPUBench cpu_DP_1thread.dat >> out.txt
./MyCPUBench cpu_DP_2thread.dat >> out.txt
./MyCPUBench cpu_DP_4thread.dat >> out.txt
./MyCPUBench cpu_HP_1thread.dat >> out.txt
./MyCPUBench cpu_HP_2thread.dat >> out.txt
./MyCPUBench cpu_HP_4thread.dat >> out.txt
./MyCPUBench cpu_QP_1thread.dat >> out.txt
./MyCPUBench cpu_QP_2thread.dat >> out.txt
./MyCPUBench cpu_QP_4thread.dat >> out.txt
./MyCPUBench cpu_SP_1thread.dat >> out.txt
./MyCPUBench cpu_SP_2thread.dat >> out.txt
./MyCPUBench cpu_SP_4thread.dat >> out.txt
./MyCPUBench cpu_DP_1thread.dat >> out.txt
./MyCPUBench cpu_DP_2thread.dat >> out.txt
./MyCPUBench cpu_DP_4thread.dat >> out.txt
./MyCPUBench cpu_HP_1thread.dat >> out.txt
./MyCPUBench cpu_HP_2thread.dat >> out.txt
./MyCPUBench cpu_HP_4thread.dat >> out.txt
./MyCPUBench cpu_QP_1thread.dat >> out.txt
./MyCPUBench cpu_QP_2thread.dat >> out.txt
./MyCPUBench cpu_QP_4thread.dat >> out.txt
./MyCPUBench cpu_SP_1thread.dat >> out.txt
./MyCPUBench cpu_SP_2thread.dat >> out.txt
./MyCPUBench cpu_SP_4thread.dat >> out.txt
./MyCPUBench cpu_DP_1thread.dat >> out.txt
./MyCPUBench cpu_DP_2thread.dat >> out.txt
./MyCPUBench cpu_DP_4thread.dat >> out.txt
./MyCPUBench cpu_HP_1thread.dat >> out.txt
./MyCPUBench cpu_HP_2thread.dat >> out.txt
./MyCPUBench cpu_HP_4thread.dat >> out.txt
./MyCPUBench cpu_QP_1thread.dat >> out.txt
./MyCPUBench cpu_QP_2thread.dat >> out.txt
./MyCPUBench cpu_QP_4thread.dat >> out.txt
./MyCPUBench cpu_SP_1thread.dat >> out.txt
./MyCPUBench cpu_SP_2thread.dat >> out.txt
./MyCPUBench cpu_SP_4thread.dat >> out.txt