#!/bin/bash

echo 'Workload	Concurrency	BlockSize	MyDiskBenchThroughput	TheoreticalThroughput	Efficiency'

./MyDiskBench disk-WR-100000-1thread.dat >> Output.txt
./MyDiskBench disk-WR-100000-2thread.dat >> Output.txt
./MyDiskBench disk-WR-100000-4thread.dat >> Output.txt
./MyDiskBench disk-WR-10000-1thread.dat >> Output.txt
./MyDiskBench disk-WR-10000-2thread.dat >> Output.txt
./MyDiskBench disk-WR-10000-4thread.dat >> Output.txt
./MyDiskBench disk-WR-1000-1thread.dat >> Output.txt
./MyDiskBench disk-WR-1000-2thread.dat >> Output.txt
./MyDiskBench disk-WR-1000-4thread.dat >> Output.txt
./MyDiskBench disk-WR-1-128thread.dat >> Output.txt
./MyDiskBench disk-WR-1-16thread.dat >> Output.txt
./MyDiskBench disk-WR-1-1thread.dat >> Output.txt
./MyDiskBench disk-WR-1-2thread.dat >> Output.txt
./MyDiskBench disk-WR-1-32thread.dat >> Output.txt
./MyDiskBench disk-WR-1-4thread.dat >> Output.txt
./MyDiskBench disk-WR-1-64thread.dat >> Output.txt
./MyDiskBench disk-WR-1-8thread.dat >> Output.txt
./MyDiskBench disk-WS-100000-1thread.dat >> Output.txt
./MyDiskBench disk-WS-100000-2thread.dat >> Output.txt
./MyDiskBench disk-WS-100000-4thread.dat >> Output.txt
./MyDiskBench disk-WS-10000-1thread.dat >> Output.txt
./MyDiskBench disk-WS-10000-2thread.dat >> Output.txt
./MyDiskBench disk-WS-10000-4thread.dat >> Output.txt
./MyDiskBench disk-WS-1000-1thread.dat >> Output.txt
./MyDiskBench disk-WS-1000-2thread.dat >> Output.txt
./MyDiskBench disk-WS-1000-4thread.dat >> Output.txt
./MyDiskBench disk-RR-100000-1thread.dat >> Output.txt
./MyDiskBench disk-RR-100000-2thread.dat >> Output.txt
./MyDiskBench disk-RR-100000-4thread.dat >> Output.txt
./MyDiskBench disk-RR-10000-1thread.dat >> Output.txt
./MyDiskBench disk-RR-10000-2thread.dat >> Output.txt
./MyDiskBench disk-RR-10000-4thread.dat >> Output.txt
./MyDiskBench disk-RR-1000-1thread.dat >> Output.txt
./MyDiskBench disk-RR-1000-2thread.dat >> Output.txt
./MyDiskBench disk-RR-1000-4thread.dat >> Output.txt
./MyDiskBench disk-RR-1-128thread.dat >> Output.txt
./MyDiskBench disk-RR-1-16thread.dat >> Output.txt
./MyDiskBench disk-RR-1-1thread.dat >> Output.txt
./MyDiskBench disk-RR-1-2thread.dat >> Output.txt
./MyDiskBench disk-RR-1-32thread.dat >> Output.txt
./MyDiskBench disk-RR-1-4thread.dat >> Output.txt
./MyDiskBench disk-RR-1-64thread.dat >> Output.txt
./MyDiskBench disk-RR-1-8thread.dat >> Output.txt
./MyDiskBench disk-RS-100000-1thread.dat >> Output.txt
./MyDiskBench disk-RS-100000-2thread.dat >> Output.txt
./MyDiskBench disk-RS-100000-4thread.dat >> Output.txt
./MyDiskBench disk-RS-10000-1thread.dat >> Output.txt
./MyDiskBench disk-RS-10000-2thread.dat >> Output.txt
./MyDiskBench disk-RS-10000-4thread.dat >> Output.txt
./MyDiskBench disk-RS-1000-1thread.dat >> Output.txt
./MyDiskBench disk-RS-1000-2thread.dat >> Output.txt
./MyDiskBench disk-RS-1000-4thread.dat >> Output.txt
